Repository microbiomedata/berkeley-schema-fy24, pull requests merged in 2024-01, with the labels that each got.

#61 1581 keep omprc typecode for class Data Generation
  src/data/invalid/DataGeneration-invalid-prefix.yaml
  src/data/valid/DataGeneration-2.yaml
  src/schema/nmdc.yaml
Labels: no-migration-needed

#53 DataGeneration child/parent relationship
  src/data/invalid/ChromatographicSeparationProcess_wrong_associated_study.yaml
  src/data/invalid/Database-data-generation-instrument_name-invalid.yaml
  src/data/invalid/Database-data-generation-undefined-omics-processing.yaml
  src/data/valid/DataGeneration-1.yaml
  src/data/valid/DataGeneration-ndsdc-bioproject.yaml
  src/data/valid/DataGeneration-processing-institution.yaml
  src/data/valid/Database-data-generations.yaml
  src/data/valid/Database-multiple-paths.yaml
  src/data/valid/Database-neon_Biosample_to_DataObject_NEON.yaml
  src/data/valid/Database-nmdc-example.yaml
  src/schema/nmdc.yaml
Labels: migration-needed

#70 1566- add permissible values to InstrumentVendorEnum and InstrumentModelEnum for sequencing applications
  src/data/valid/Database-instrument_set.yaml
  src/data/valid/Instrument-basic.yaml
  src/schema/nmdc.yaml
Labels: migration-needed

#79 1736 add associated studies to biosample
  nmdc_schema/test_more_tolerant_schema.py
  src/data/invalid/Biosample-incomplete_napa_id.yaml
  src/data/invalid/Biosample-invalid_fire.yaml
  src/data/invalid/Biosample-minimal-invalid-type.yaml
  src/data/invalid/Biosample-minimal-no-id-but-with-type.yaml
  src/data/invalid/Biosample-minimal-no-type.yaml
  src/data/invalid/Biosample-non_boolean_embargo.yaml
  src/data/invalid/Database-Biosample-invalid_id.yaml
  src/data/invalid/Database-Biosample-invalid_lat_lon_ranges.yaml
  src/data/invalid/Database-biosample_gold_id_list_as_primary_key.yaml
  src/data/invalid/Database-biosample_undeclared_slot.yaml
  src/data/invalid/Database-biosamples-dna-in-bucket.yaml
  src/data/invalid/Database-biosamples-dna-in-plate-invalid-well-val.yaml
  src/data/invalid/Database-biosamples-dna-in-plate-no-well-val.yaml
  src/data/invalid/Database-biosamples-dna-in-tube-with-well-value.yaml
  src/data/invalid/Database-biosamples-high-rna_volume.yaml
  src/data/invalid/Database-biosamples-lat_lon-with-GLV-missing-latitude.yaml
  src/data/invalid/Database-biosamples-lat_lon-with-GLV-missing-longitude.yaml
  src/data/invalid/Database-biosamples-rna-in-bucket.yaml
  src/data/invalid/Database-biosamples-rna-in-plate-invalid-well-val.yaml
  src/data/invalid/Database-biosamples-rna-in-plate-no-well-val.yaml
  src/data/invalid/Database-biosamples-rna-in-tube-with-well-value.yaml
  src/data/invalid/Database-data-generation-instrument_name-invalid.yaml
  src/data/invalid/Database-data-generation-undefined-omics-processing.yaml
  src/data/valid/Biosample-embargoed.yaml
  src/data/valid/Biosample-minimal.yaml
  src/data/valid/Biosample-soil_horizon.yaml
  src/data/valid/Biosample-with-fire.yaml
  src/data/valid/Database-biosample-exhasutive.yaml
  src/data/valid/Database-biosample_set_low-but-acceptable-rna_volume.yaml
  src/data/valid/Database-biosamples-1.yaml
  src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml
  src/data/valid/Database-biosamples-dna-in-tube.yaml
  src/data/valid/Database-biosamples-minimal.yaml
  src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml
  src/data/valid/Database-biosamples-rna-in-tube.yaml
  src/data/valid/Database-biosamples-sites.yaml
  src/data/valid/Database-multiple-paths.yaml
  src/data/valid/Database-neon-story.yaml
  src/data/valid/Database-neon_Biosample_to_DataObject_NEON.yaml
  src/data/valid/Database-nmdc-example.yaml
  src/data/valid/NucleotideSequencing-2.yaml
  src/schema/nmdc.yaml
  tests/test_biosample_instantiation.py
Labels: migration-needed, migrator-written
